Todo features
helciodev/todo-list-app pull request #2
Opened 2021-06-01 18:42 UTC by helciodev

The features of this project are, user can:

1. Create lists of todo.
2. Add tasks to each list.
3. Delete and edit tasks
4. Delete lists

2021-06-01 19:42 UTC, SajjadAhmad14 commented on src/index.js
> +}
Please use the arrow function here,

2021-06-01 19:43 UTC, SajjadAhmad14 commented on src/index.js
> +}
Please use the arrow function here,

2021-06-01 19:43 UTC, SajjadAhmad14 commented on src/index.js
> +}
Please use the arrow function here,

2021-06-01 19:43 UTC, SajjadAhmad14 commented on src/index.js
> +}
Please use the arrow function here,

2021-06-01 19:44 UTC, SajjadAhmad14 commented on src/index.js
> +}
Please use the arrow function here,

2021-06-01 19:44 UTC, SajjadAhmad14 commented on src/index.js
> +}
Please use the arrow function here,

2021-06-01 19:44 UTC, SajjadAhmad14 commented on src/index.js
> +}
Please use the arrow function here,

2021-06-01 19:47 UTC, SajjadAhmad14 commented on src/index.js
> +      taskRenderFn();
DOM manipulation and app logic should be completely separate.

2021-06-01 19:47 UTC, SajjadAhmad14 commented on src/index.js
> +});
DOM manipulation and app logic should be completely separate.

2021-06-01 19:48 UTC, SajjadAhmad14 commented on src/index.js
> +});
DOM manipulation and app logic should be completely separate.

2021-06-01 19:49 UTC, SajjadAhmad14 requested changes
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [ ] You have mastered Git flow.
- [ ] README is professional contains all the info to run the project locally.
- [ ] Your app UI is pleasing.
## To Improve 🙏
- [ ] Please see inline comments for reference.
- [ ] You have all your code in one file. Please separate your code into different modules. It's easy to manage code and debug in modules.
- [ ] DOM-Manipulation and Logic are in separate modules. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/modules_requirement.png).
- [ ] There should be one default project.
- [ ] Please use ES6 syntax. Use arrow functions instead of function keywords.

### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

2021-06-03 13:31 UTC, Berabjesus approved these changes
# **Status: PROJECT APPROVED** 
Hey @helciodev great job implementing the changes required by the previous reviewer.
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete. 👍** 

### **Before you merge to the default branch please have a look at the following OPTIONAL comments below.**

- [ ] [OPTIONAL] The MVC way of approach you have used here means that the model section of your code should be responsible for data access, in this case handling local storage. Currently, the model section looks more like a helper than a model. Please have a look into that.

I wish you all the very best in your next tasks:1st_place_medal:
#### **If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help** 
**HAPPY CODING :computer:[Bereket Beshane](https://bereketababu.me)** | [LinkedIn](https://linkedin.com/in/bereketbeshane) | [GitHub](https://github.com/Berabjesus)

2021-06-03 14:26 UTC, merged